service: serverless-articular

app: serverless-articular
org: dinushankanrg
plugins:
  - serverless-dotenv-plugin
  - serverless-mocha-plugin
  - serverless-offline

custom:
  dotenv:
    basePath: ./env/

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'development'}
  region: ap-south-1
  environment:
    env: ${file(./env/.env.${self:provider.stage})}

functions:
  u:
    handler: src/users/users.handler
    events:
      - http:
          path: '/v1/users/{proxy+}'
          method: any
          cors: true
  a:
    handler: src/topics/topics.handler
    events:
      - http:
          path: '/v1/topics/{proxy+}'
          method: any
          cors: true
  t:
    handler: src/articles/articles.handler
    events:
      - http:
          path: '/v1/articles/{proxy+}'
          method: any
          cors: true

